### ISSUE TITLE
maxDistance unclear

### ISSUE THREAD

**Issue by AleksandarFaraj** [mourner/rbush-knn#13]
Hello!

I noticed that the explanation for maxDistance is lacking after getting some bad results and reading the source code. Perhaps this is some domain specific knowledge for cartographers, but it was unclear for me. 

`maxDistance (optional): maximum distance between neighbours and the query coordinates (Infinity by default)`

It's not clear that the distance should be expressed as distance^2. 

Taking the pythagoras theorem into account: a^2+b^2=c^2

The functions boxDist returns a^2+b^2, but is comparing to c^1 not c^2

From index.js
```
            dist = boxDist(x, y, node.leaf ? toBBox(child) : child);
            if (!maxDistance || dist <= maxDistance) {
```

From index.js
```
function boxDist(x, y, box) {
    var dx = axisDist(x, box.minX, box.maxX),
        dy = axisDist(y, box.minY, box.maxY);
    return dx * dx + dy * dy;
}
```

Suggestion: 
1) square maxDistance (maxDistance = maxDistance * maxDistance) in index.js or, 
2) change the readme

**Comment by mourner** [comment]
Oh, I think this is actually a bug — it was supposed to be `maxDistance * maxDistance` in the comparison. Would you submit a PR with a fix + tests?

**Comment by thisredone** [comment]
@mourner please merge  #14 and publish a new version when you get a chance :)

**Comment by mourner** [comment]
Done!
