### ISSUE TITLE
Doesn't return nearest neighbor

### ISSUE THREAD

**Issue by darabos** [mourner/rbush-knn#20]
I'm getting some unexpected results from `knn`, like it ignores some of my points.

```javascript
const tree = new RBush();
tree.load([
  [0, 0],
  [10, 10],
  ]);
console.log(knn(tree, 0, 0, 1)); // Prints [[10, 10]].
```
([Observable notebook](https://observablehq.com/d/c7524c382d77b478))

Why doesn't it print `[[0, 0]]`? Am I doing something wrong?

Thanks!

**Comment by mourner** [comment]
RBush expects a different data format, not pairs of numbers. See https://github.com/mourner/rbush#data-format

**Comment by darabos** [comment]
> RBush expects a different data format, not pairs of numbers. See https://github.com/mourner/rbush#data-format

Oh, sorry! Thanks a lot! I switched to https://github.com/ubilabs/kd-tree-javascript in the meantime but now I've switched back. `rbush-knn` is faster in my application!

**Comment by mourner** [comment]
@darabos great! Also, if you don't insert/remove points dynamically after the initial load, you might want to look at https://github.com/mourner/flatbush which is by far the fastest.

**Comment by darabos** [comment]
Ah, thanks, that's very helpful! I found https://github.com/mourner/kdbush but somehow missed Flatbush. Perfect.
