### ISSUE TITLE
Distance cutoff

### ISSUE THREAD

**Issue by danburzo** [mourner/rbush-knn#7]
Hi there, I wanted to ask if it sounds like a good idea to send the box distance as the second parameter to the _filter function_ (predicate), to enable checking that the returned items are not further away than a certain distance. 

I realize this can already be achieved with the available item data (minX, maxX, etc.) and furthermore a distance cutoff may not efficiently be implemented in the filter itself — since returning false after the candidates get too far away will only cause the tree to be queried further (to fill in K items) with no chance of later items to be closer. 

May be that a separate argument for the cutoff would be better suited? (If, of course, it's in the scope of this library)

**Comment by mourner** [comment]
Yes, I think it would be very useful, but I'm thinking of adding a separate argument (`maxDistance`) to the search function rather than the predicate to make it more efficient and easier to use. This is the route I took in https://github.com/mourner/geokdbush
